#define FIRST_ROCK_TILE_FRAME	8
#define NUM_FRAMES_PER_DEPTH	8

const char meta_tile_maps[] PROGMEM = {

0,0,//blank
0,0,

14,6,//left end
16,7,

6,6,//horizontal middle
7,7,

6,15,//right end
7,17,

10,11,//top end
8,9,

8,9,//vertical middle
8,9,

8,9,//bottom end
16,17,

5,5,//dirt layer 0
5,5,

1,2,//rock layer 0
3,4,

10,11,//tunnel up long divet layer 0
8,9,

0,0,//tunnel up short divet layer 0
10,11,

8,9,//tunnel down long divet layer 0
12,13,

12,13,//tunnel down short divet layer 0
5,5,

14,6,//tunnel left long divet layer 0
16,7,

5,14,//tunnel left short divet layer 0
5,16,



22,22,//dirt layer 1
22,22,

18,19,//rock layer 1
20,21,

39,39,//dirt layer 2
39,39,

35,36,//rock layer 2
37,38,

56,56,//dirt layer 3
56,56,

52,53,//rock layer 3
54,55,


#define FIRST_VEGGIE_FRAME 21

81,82,//carrot
83,84,

85,86,//turnip
87,88,

89,90,//mushroom
91,92,

255,93,//cucumber
94,95,

96,97,//egg plant
98,99,

100,101,//green pepper
102,103,

104,105,//tomato
106,107,

108,109,//garlic
110,111,

112,113,//watermelon
114,115,

116,117,//glaxian ship
118,119,

120,121,//pineapple
122,123,



};
