<?xml version="1.0" ?>
<gfx-xform version="1">
    <input file="/home/flavio/imagens/urbanmess.raw" type="raw" tile-width="8" tile-height="8" width="96" height="80" />
    <output file="/home/flavio/uzebox/work/urbanmess.inc">
        <tiles var-name="uMTiles"/>
        <maps pointers-size="8">
	    <map var-name="map_graffiti" left="0" top="2" width="3" height="4"/>
	    <map var-name="map_title" left="3" top="0" width="9" height="7"/>
	    <map var-name="map_window" left="0" top="7" width="2" height="2"/>			
	</maps>	
    </output>
</gfx-xform>