const char BorderFrames[] PROGMEM ={
//TOP
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
1,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,5,
//LEFT
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
1,6,
//RIGHT
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,
7,5,

255,
};


const char BorderTable[] PROGMEM ={//1 for each level...
0, //START FRAME(IS ABSOLUTE OFFSET INTO FRAME TABLE)
1, //NUM FRAMES(FRAMES MUST BE SEQUENTIAL)
};

const char BorderFrameTimes[] PROGMEM ={
30,30,

};