const unsigned char Palette1[] PROGMEM = {

};

const unsigned char Palette2[] PROGMEM = {

};

const unsigned char Palette3[] PROGMEM = {

};

const unsigned char Palette4[] PROGMEM = {

};

const unsigned char Palette5[] PROGMEM = {

};

const unsigned char Palette6[] PROGMEM = {

};

const unsigned char Palette7[] PROGMEM = {

};

const unsigned char PaletteBonus[] PROGMEM = {

};
