/* Created with Uzebox Patch Studio 0.0.1 */
const char patch00[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 70,
  2, PC_ENV_SPEED, -2,
  0, PC_PITCH, 64,
  2, PC_PITCH, 71,
  2, PC_PITCH, 64,
  2, PC_PITCH, 71,
  2, PC_PITCH, 64,
  2, PC_PITCH, 71,
  2, PC_PITCH, 64,
  2, PC_PITCH, 71,
  0, PATCH_END,
};

const char patch01[] PROGMEM = {
  0, PATCH_END,
};
const char patch02[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 79,
  1, PC_PITCH, 67,
  1, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch03[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 60,
  1, PC_PITCH, 48,
  1, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch04[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 67,
  1, PC_PITCH, 55,
  1, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch05[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 108,
  2, PC_NOTE_DOWN, 2,
  3, PC_NOTE_DOWN, 2,
  3, PC_NOTE_DOWN, 2,
  3, PC_NOTE_DOWN, 2,
  2, PC_NOTE_DOWN, 2,
  2, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch06[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 55,
  1, PC_PITCH, 52,
  1, PC_PITCH, 48,
  1, PC_PITCH, 45,
  1, PC_PITCH, 55,
  1, PC_PITCH, 52,
  1, PC_PITCH, 48,
  1, PC_PITCH, 45,
  1, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch07[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_VOL, 66,
  0, PC_ENV_SPEED, -5,
  0, PC_PITCH, 45,
  2, PC_PITCH, 57,
  12, PC_ENV_VOL, 66,
  2, PC_PITCH, 45,
  6, PC_PITCH, 57,
  1, PC_ENV_VOL, 66,
  0, PC_ENV_SPEED, -2,
  2, PC_PITCH, 45,
  1, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch08[] PROGMEM = {
  0, PC_WAVE, 0,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 60,
  3, PC_PITCH, 72,
  3, PC_PITCH, 79,
  3, PC_PITCH, 84,
  3, PC_PITCH, 60,
  3, PC_PITCH, 72,
  3, PC_PITCH, 79,
  3, PC_PITCH, 84,
  3, PC_ENV_SPEED, -8,
  0, PATCH_END,
};

const char patch09[] PROGMEM = {
  0, PC_WAVE, 8,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 60,
  1, PC_PITCH, 61,
  2, PC_PITCH, 60,
  1, PC_PITCH, 59,
  2, PC_PITCH, 58,
  2, PC_PITCH, 57,
  2, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch09b[] PROGMEM = {
  0, PC_WAVE, 4,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 60,
  1, PC_PITCH, 61,
  2, PC_PITCH, 60,
  1, PC_PITCH, 59,
  2, PC_PITCH, 58,
  2, PC_PITCH, 57,
  2, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch10[] PROGMEM = {
  0, PC_WAVE, 5,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_SPEED, -4,
  0, PC_PITCH, 69,
  0, PC_ENV_VOL, 66,
  16, PC_ENV_VOL, 66,
  16, PC_ENV_VOL, 66,
  2, PC_ENV_SPEED, -3,
  0, PATCH_END,
};
const char patch10b[] PROGMEM = {
  0, PC_WAVE, 8,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_SPEED, -4,
  0, PC_PITCH, 69,
  0, PC_ENV_VOL, 66,
  16, PC_ENV_VOL, 66,
  16, PC_ENV_VOL, 66,
  2, PC_ENV_SPEED, -3,
  0, PATCH_END,
};

const char patch11[] PROGMEM = {
  0, PC_WAVE, 5,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_SPEED, -4,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 72,
  2, PC_ENV_VOL, 66,
  0, PC_PITCH, 73,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 74,
  13, PC_ENV_VOL, 66,
  0, PC_PITCH, 73,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 74,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 75,
  9, PC_ENV_VOL, 66,
  0, PC_PITCH, 74,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 75,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 77,
  8, PC_ENV_VOL, 66,
  0, PC_PITCH, 76,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 77,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 78,
  6, PC_ENV_VOL, 66,
  0, PC_PITCH, 78,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 79,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 81,
  0, PATCH_END,
};
const char patch12[] PROGMEM = {

  0, PC_WAVE, 9,
  0, PC_TREMOLO_LEVEL,133,
  0, PC_TREMOLO_RATE,188,
  0, PC_ENV_SPEED, -12,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 60,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 76,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 79,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 64,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 79,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 67,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 86,

  0, PC_ENV_SPEED, -14,
 // 0, PC_WAVE, 5,

  3, PC_ENV_VOL, 30,
  0, PC_PITCH, 60,
  3, PC_ENV_VOL, 30,
  0, PC_PITCH, 76,
  3, PC_ENV_VOL, 30,
  0, PC_PITCH, 79,
  3, PC_ENV_VOL, 30,
  0, PC_PITCH, 64,
  3, PC_ENV_VOL, 30,
  0, PC_PITCH, 79,
  3, PC_ENV_VOL, 30,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 30,
  0, PC_PITCH, 67,
  3, PC_ENV_VOL, 25,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 20,
  0, PC_PITCH, 86,


  3, PATCH_END,
/*
 	0,PC_WAVE,1,//modified from Alter Ego
	0,PC_ENV_VOL,132,
	0,PC_ENV_SPEED,-1,
	0,PC_PITCH,67,
	5,PC_PITCH,79,
	5,PC_PITCH,72,
	5,PC_PITCH,84,
	//0,PC_ENV_VOL,64,
	0,PC_ENV_SPEED,-2,
	5,PC_PITCH,67,
	5,PC_PITCH,79,
	5,PC_PITCH,72,
	5,PC_PITCH,84,
	//0,PC_ENV_VOL,34,
	0,PC_ENV_SPEED,-4,
	5,PC_PITCH,67,
	5,PC_PITCH,79,
	5,PC_PITCH,72,
	5,PC_PITCH,84,
	1,PC_NOTE_CUT,0,
0,PATCH_END
*/
};
const char patch13[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 66,
  0, PC_ENV_SPEED, -4,
  0, PC_PITCH, 84,
  6, PC_ENV_VOL, 66,
  0, PC_PITCH, 72,
  6, PC_ENV_VOL, 66,
  0, PC_PITCH, 84,
  6, PC_ENV_VOL, 66,
  0, PC_PITCH, 72,
  0, PATCH_END,
};
const char patch13b[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 66,
  0, PC_ENV_SPEED, -4,
  0, PC_PITCH, 84,
  6, PC_ENV_VOL, 66,
  0, PC_PITCH, 72,
  6, PC_ENV_VOL, 66,
  0, PC_PITCH, 84,
  6, PC_ENV_VOL, 66,
  0, PC_PITCH, 72,
  0, PATCH_END,
};
const char patch14[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 66,
  0, PC_ENV_SPEED, -3,
  0, PC_PITCH, 69,
  16, PC_ENV_VOL, 66,
  0, PC_PITCH, 69,
  24, PC_ENV_VOL, 66,
  0, PC_PITCH, 69,
  0, PATCH_END,
};
const char patch14b[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_ENV_VOL, 66,
  0, PC_ENV_SPEED, -2,
  0, PC_PITCH, 69,
  16, PC_ENV_VOL, 66,
  0, PC_PITCH, 69,
  24, PC_ENV_VOL, 66,
  0, PC_PITCH, 69,
  0, PATCH_END,
};
const char patch15[] PROGMEM = {
  0, PC_WAVE, 5,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_PITCH, 60,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 76,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 86,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 60,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 76,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 79,
  3, PC_ENV_VOL, 66,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 79,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 67,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 83,
  0, PC_PITCH, 86,
  3, PATCH_END,
};
const char patch16[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 47,
  1, PC_PITCH, 48,
  1, PC_PITCH, 49,
  1, PC_PITCH, 50,
  1, PC_PITCH, 51,
  1, PC_PITCH, 52,
  1, PC_PITCH, 53,
  1, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch17[] PROGMEM = {
  0, PC_WAVE, 3,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_VOL, 66,
  0, PC_PITCH, 47,
  1, PC_PITCH, 48,
  1, PC_PITCH, 49,
  1, PC_PITCH, 50,
  1, PC_PITCH, 51,
  1, PC_PITCH, 52,
  1, PC_PITCH, 53,
  1, PC_ENV_SPEED, -8,
  0, PATCH_END,
};
const char patch18[] PROGMEM = {
  0, PC_WAVE, 5,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_PITCH, 60,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 76,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 86,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 60,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 76,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 79,
  3, PC_ENV_VOL, 66,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 79,
  0, PC_PITCH, 83,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 67,
  3, PC_ENV_VOL, 66,
  0, PC_PITCH, 83,
  0, PC_PITCH, 86,
  3, PATCH_END,
};
const char patch19[] PROGMEM = {
  0, PC_WAVE, 5,
  0, PC_TREMOLO_LEVEL, 111,
  0, PC_TREMOLO_RATE, 88,
  0, PC_ENV_SPEED, -4,
  0, PC_PITCH, 60,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 57,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 52,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 48,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 47,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 60,
  4, PC_ENV_VOL, 66,
  0, PC_PITCH, 55,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 52,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 48,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 45,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 40,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 59,
  4, PC_ENV_VOL, 66,
  0, PC_PITCH, 55,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 52,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 48,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 45,
  1, PC_ENV_VOL, 66,
  0, PC_PITCH, 40,
  3, PATCH_END,
};
const char patch20[] PROGMEM = {
  0, PC_WAVE, 5,
  0, PC_ENV_VOL, 66,
  0, PC_LOOP_START, 20,
  0, PC_PITCH, 84,
  1, PC_PITCH, 83,
  1, PC_LOOP_END, 2,
  1, PC_ENV_SPEED, -8,
  0, PATCH_END,
};

const char patch21[] PROGMEM = {};
const char patch22[] PROGMEM = {};
const char patch23[] PROGMEM = {};
const char patch24[] PROGMEM = {};
const char patch25[] PROGMEM = {};

const char patch26[] PROGMEM = {
  0,PC_WAVE,4,
  0,PC_ENV_SPEED,-6,
  0,PATCH_END,
};

const char patch27[] PROGMEM = {
  0,PC_WAVE,4,
  0,PC_ENV_SPEED,-6,
  0,PATCH_END,
};

const char patch28[] PROGMEM = {
  0,PC_WAVE,4,
  0,PC_ENV_SPEED,-6,
  0,PATCH_END,
};

const char patch29[] PROGMEM = {
  0,PC_WAVE,4,
  0,PC_ENV_SPEED,-6,
  0,PATCH_END,
};

const char patch30[] PROGMEM = {
  0,PC_WAVE,4,
  0,PC_ENV_SPEED,-6,
  0,PATCH_END,
};

const struct PatchStruct patches[] PROGMEM = {
//sfx
{0,NULL,patch00,0,0},//
{0,NULL,patch01,0,0},//
{0,NULL,patch02,0,0},//
{0,NULL,patch03,0,0},//
{0,NULL,patch04,0,0},//
{0,NULL,patch05,0,0},//
{0,NULL,patch06,0,0},//
{0,NULL,patch07,0,0},//
{0,NULL,patch08,0,0},//
{0,NULL,patch09,0,0},//plays with patch09b
{0,NULL,patch10,0,0},//plays with patch10b
{0,NULL,patch11,0,0},//
{0,NULL,patch12,0,0},//
{0,NULL,patch13,0,0},//plays with patch13b
{0,NULL,patch14,0,0},//plays with patch14b
{0,NULL,patch15,0,0},//TODO
{0,NULL,patch16,0,0},//
{0,NULL,patch17,0,0},//TODO
{0,NULL,patch18,0,0},//TODO
{0,NULL,patch19,0,0},//
{0,NULL,patch20,0,0},//
{0,NULL,patch21,0,0},//placeholder
{0,NULL,patch22,0,0},//..
{0,NULL,patch23,0,0},//..
{0,NULL,patch24,0,0},//..
{0,NULL,patch25,0,0},//..
{0,NULL,patch26,0,0},//intro song lead instrument
{0,NULL,patch27,0,0},
{0,NULL,patch28,0,0},
{0,NULL,patch29,0,0},
{0,NULL,patch30,0,0},
//instruments
};
