const char BaseAnim[] PROGMEM = {//first animation per enemy type
0,//snakey
0,//medusa
0,//don
0,//gol
0,//alma
0,//leeper
0,//skull
0,//rocky
0,//moby
0,//enemyexplode
0,//dummy
0,//lolo
};

const char AnimTable[] PROGMEM = {//frame,frametime,frame,...
255,255,255,255,255,255,255,255,255,255,255,255,
0,8,1,8,255,//don
//alma frames 4 ticks
0,2,0,2,//lolo frames 2 ticks
};

const char FrameTable[] PROGMEM = {
//don 1

//don 2
};



const char MirrorTable[] PROGMEM = {

};